# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180104_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testdata',
            new_name='Depthdata',
        ),
    ]
