# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_instructors',
            new_name='instructors',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_start_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Notes'),
        ),
    ]
