# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20171231_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Scheduling', 'verbose_name_plural': 'Scheduling'},
        ),
    ]
