# Generated by Django 2.0 on 2018-01-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20171231_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number',
            field=models.CharField(help_text='Session ID', max_length=5, null=True, verbose_name='Session ID'),
        ),
    ]
