# Generated by Django 2.0 on 2018-01-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_event_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.CharField(help_text='Instructor(s)', max_length=50, null=True, verbose_name='Instructor(s)'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(help_text='Location', max_length=25, null=True, verbose_name='Location'),
        ),
    ]
