# Generated by Django 2.0 on 2018-01-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(help_text='Day of the event in JJJJ/MM/DD', verbose_name='Day of the event'),
        ),
    ]
