# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_colorsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorsetting',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='colorsetting',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
